name: maxi_common
description: A new Flutter package project.
version: 0.0.1
# homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.12.29
  auto_route: ^5.0.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_riverpod: ^1.0.4
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  dartz: ^0.10.1
  location: ^4.4.0
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.3+1


flutter:
